### ISSUE TITLE
i have used nova API in Nova Version of Open-interpreter, and i got Incorrect API key provided: nv-ThHDF***************************************nq60. You can find your API key at https://platform.openai.com/account/api-keys.

### ISSUE THREAD

**Issue by amrpyt** [NovaOSS/nova-api#15]
i have used nova API in **Open-interpreter Nova Version**, and i got:
 Incorrect API key provided: nv-ThHDF***************************************nq60. You can find your API key at https://platform.openai.com/account/api-keys.

**Comment by nsde** [comment]
Sorry, the repository for the Nova version of open-interpreter hasn't been updated.
The issue is related to that repository.
