### ISSUE TITLE
Github Actions for testing

### ISSUE THREAD

**Issue by RayBytes** [NovaOSS/nova-api#8]
We currently don't have a really good way to test new pull requests, what do you guys think about using github actions for testing instead? That way all pull requests can be easily tested upon pull.

I can begin working on it if it is something we want to create.

**Comment by nsde** [comment]
Sure

**Comment by RayBytes** [comment]
@nsde You will need to add api keys as github secrets so that the github actions bot can retrieve those keys for the tests

**Comment by nsde** [comment]
> api keys 
Do I also need to add my whole `.env` there (proxy configuration, MongoDB URI etc.)?

**Comment by RayBytes** [comment]
> > api keys
> 
> Do I also need to add my whole `.env` there (proxy configuration, MongoDB URI etc.)?

Anything which the tests need has to be a git secret.

**Comment by nsde** [comment]
> > > api keys
> > 
> > 
> > Do I also need to add my whole `.env` there (proxy configuration, MongoDB URI etc.)?
> 
> Anything which the tests need has to be a git secret.

that's not very secure
would it really be worth it? 🤔 

![image](https://github.com/NovaOSS/nova-api/assets/67185896/60915c34-e04c-49ec-8b90-4b4b4da6a2f8)

**Comment by RayBytes** [comment]
@nsde its a git secret. How is anyone else going to get access to it (unless you give them that perm ofc)

**Comment by RayBytes** [comment]
@nsde what permissions have you given people to this repo? I know myself, but which people and what permissions have you given? Only collab's can see github secrets.

**Comment by nsde** [comment]
Just admins have full permissions.

**Comment by nsde** [comment]
Thanks @RayBytes !
![image](https://github.com/NovaOSS/nova-api/assets/67185896/44f2a4aa-2d8b-468f-be85-805804166cab)
